### ISSUE TITLE
ExperimentalWarning when using Meow with modules

### ISSUE THREAD

**Issue by GBrachetta** [sindresorhus/meow#220] opened 2022-12-01 09:27 UTC
I'm using Meow in a CLI  which uses modules rather than common imports (`import meow from 'meow'`), and I get a warning when, for example, I use the built-in `--version` flag, saying that importing JSON modules is an experimental feature:

```
(node:83927) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

Obviously this pollutes the output.

Is there a way to hide this warning?

**Comment by sindresorhus** [comment] 2022-12-04 19:21
I'm unable to reproduce this. What Node.js and Meow version?

**Comment by sindresorhus** [comment] 2022-12-06 14:50
Closing as this is not a problem with Meow.

**Comment by sindresorhus** [comment] 2022-12-06 14:51
Meow returns the package data, so not sure why you are importing it yourself.

**Closed by sindresorhus** 2022-12-06 14:50 UTC
