### ISSUE TITLE
typescript definitions stopped working

### ISSUE THREAD

**Issue by chase-moskal** [sindresorhus/meow#248] opened 2023-11-04 05:47 UTC
hello! love the library!

i upgraded meow, and the typescript typings seem to have stopped working

- ✅ `meow@12.0.1` all good
    - this version of the package has this exports field:
        ```json
        "exports": {
            "types": "./index.d.ts",
            "default": "./source/index.js"
        },
        ```
- ❌ `meow@12.1.1` gives me a typescript error:
    - `TS2307: Cannot find module 'meow' or its corresponding type declarations.`
    - the error points at this line:
        ```ts
        import meow from "meow"
        ```
    - this version of the package has this exports field:
        ```json
        "exports": {
            "types": "./build/index.d.ts",
            "default": "./build/index.js"
        },
        ```

i don't understand what's going wrong, since i can see at the [unpkg browse link for meow@12.1.1](https://unpkg.com/browse/meow@12.1.1/build/) that the export field links to index.d.ts and index.js look correct to me :man_shrugging: 

i'm on node v21.1.0 and typescript 5.2.2

in the meantime as a workaround i added a file called `module-declarations.d.ts` to my codebase with the following content, which worked to suppress the typescript error
```ts
declare module "meow"
```

hopefully this info helps, cheers :heart:

**Comment by sindresorhus** [comment] 2023-11-04 06:47
Duplicate of #247

**Closed by sindresorhus** 2023-11-04 06:47 UTC

**Comment by chase-moskal** [comment] 2023-11-05 09:10
thanks,

the solution was to set these settings in my `tsconfig.json`:

```json
"module": "nodenext",
"moduleResolution": "nodenext",
```

this is required for `meow`, however it should be noted that you could also have dependencies that do not yet support `nodenext`, such as https://github.com/BabylonJS/Babylon.js/issues/13797 which was an issue i encountered in some of my projects
